### ISSUE TITLE
Mieux gérer les logs pour tous les services de l'infra des données

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/qualite-des-donnees#49]

**Comment by sixtedemaupeou** [comment]
Progrès fait sur le 3 services. Sur analysis et hydra il ne reste plus qu'à voir si on peut générer des logs debug sans avoir les logs debug de Kafka. Sur csvapi il reste encore un peu de dev.

**Comment by maudetes** [comment]
Système avec variable d'environnement pour setter le niveau de log :)
